// aliases: ['add_to_drive', 'add_moderator', 'add_link', 'add_chart', 'add_call'],
export const customIconList = [
    {
        name: '1k_plus',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    { name: '19mp', version: -1, unsupported_families: [], categories: [], tags: [], sizes_px: [] },
    {
        name: '18mp',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    { name: '17mp', version: -1, unsupported_families: [], categories: [], tags: [], sizes_px: [] },
    {
        name: '16mp',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    { name: '15mp', version: -1, unsupported_families: [], categories: [], tags: [], sizes_px: [] },
    {
        name: '14mp',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    { name: '13mp', version: -1, unsupported_families: [], categories: [], tags: [], sizes_px: [] },
    {
        name: '12mp',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    { name: '11mp', version: -1, unsupported_families: [], categories: [], tags: [], sizes_px: [] },
    {
        name: '10mp',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    { name: '10k', version: -1, unsupported_families: [], categories: [], tags: [], sizes_px: [] },
    {
        name: '1k',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    { name: '2k_plus', version: -1, unsupported_families: [], categories: [], tags: [], sizes_px: [] },
    {
        name: '24mp',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    { name: '23mp', version: -1, unsupported_families: [], categories: [], tags: [], sizes_px: [] },
    {
        name: '22mp',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    { name: '21mp', version: -1, unsupported_families: [], categories: [], tags: [], sizes_px: [] },
    {
        name: '20mp',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    { name: '2mp', version: -1, unsupported_families: [], categories: [], tags: [], sizes_px: [] },
    {
        name: '2k',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    { name: '3k_plus', version: -1, unsupported_families: [], categories: [], tags: [], sizes_px: [] },
    {
        name: '3mp',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    { name: '3k', version: -1, unsupported_families: [], categories: [], tags: [], sizes_px: [] },
    {
        name: '4k_plus',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    { name: '4mp', version: -1, unsupported_families: [], categories: [], tags: [], sizes_px: [] },
    {
        name: '5mp',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    { name: '5k_plus', version: -1, unsupported_families: [], categories: [], tags: [], sizes_px: [] },
    {
        name: '5k',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    { name: '6mp', version: -1, unsupported_families: [], categories: [], tags: [], sizes_px: [] },
    {
        name: '6k_plus',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    { name: '6k', version: -1, unsupported_families: [], categories: [], tags: [], sizes_px: [] },
    {
        name: '7k_plus',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    { name: '7mp', version: -1, unsupported_families: [], categories: [], tags: [], sizes_px: [] },
    {
        name: '7k',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    { name: '8k_plus', version: -1, unsupported_families: [], categories: [], tags: [], sizes_px: [] },
    {
        name: '8mp',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    { name: '8k', version: -1, unsupported_families: [], categories: [], tags: [], sizes_px: [] },
    {
        name: '9k_plus',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    { name: '9mp', version: -1, unsupported_families: [], categories: [], tags: [], sizes_px: [] },
    {
        name: '9k',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'auto_stories',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'auto_fix_off',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'auto_fix_normal',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'auto_fix_high',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'auto_awesome_motion',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'auto_awesome_mosaic',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'auto_awesome',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'attractions',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'assistant_navigation',
        version: -1,
        unsupported_families: [],
        categories: ['navigation'],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'assistant_direction',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'approval',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'app_registration',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'animation',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'airplanemode_on',
        version: -1,
        unsupported_families: [],
        categories: ['device'],
        tags: [],
        sizes_px: [],
        aliasOf: 'airplanemode_active',
    },
    {
        name: 'airplanemode_off',
        version: -1,
        unsupported_families: [],
        categories: ['device'],
        tags: [],
        sizes_px: [],
        aliasOf: 'airplanemode_inactive',
    },
    {
        name: 'add_to_drive',
        version: -1,
        unsupported_families: [],
        categories: ['action'],
        tags: [],
        sizes_px: [],
        aliasOf: 'add',
    },
    {
        name: 'add_moderator',
        version: -1,
        unsupported_families: [],
        categories: ['action'],
        tags: [],
        sizes_px: [],
        aliasOf: 'add',
    },
    {
        name: 'add_link',
        version: -1,
        unsupported_families: [],
        categories: ['content'],
        tags: [],
        sizes_px: [],
        aliasOf: 'add',
    },
    {
        name: 'add_chart',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
        aliasOf: 'add',
    },
    {
        name: 'add_call',
        version: -1,
        unsupported_families: [],
        categories: ['communication'],
        tags: [],
        sizes_px: [],
        aliasOf: 'add_ic_call',
    },
    {
        name: 'bus_alert',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
        aliasOf: 'add',
    },
    {
        name: 'brunch_dining',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'breakfast_dining',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'border_color',
        version: -1,
        unsupported_families: [],
        categories: ['editor'],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'bookmark_outline',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    { name: 'bolt', version: -1, unsupported_families: [], categories: [], tags: [], sizes_px: [] },
    {
        name: 'block_flipped',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    { name: 'bakery_dining', version: -1, unsupported_families: [], categories: [], tags: [], sizes_px: [] },
    {
        name: 'badge',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'connected_tv',
        version: -1,
        unsupported_families: [],
        categories: ['av'],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'confirmation_num',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'compress',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'closed_caption_off',
        version: -1,
        unsupported_families: [],
        categories: ['av'],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'circle_notifications',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    { name: 'circle', version: -1, unsupported_families: [], categories: [], tags: [], sizes_px: [] },
    {
        name: 'cell_wifi',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    { name: 'celebration', version: -1, unsupported_families: [], categories: [], tags: [], sizes_px: [] },
    {
        name: 'cases',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'car_repair',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'car_rental',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'dry_cleaning',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'drive_folder_upload',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'drive_file_rename_outline',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'drive_file_move_outline',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'drive_file_move',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'do_not_disturb_on',
        version: -1,
        unsupported_families: [],
        categories: ['notification'],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'do_not_disturb_off',
        version: -1,
        unsupported_families: [],
        categories: ['notification'],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'do_not_disturb_alt',
        version: -1,
        unsupported_families: [],
        categories: ['notification'],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'do_not_disturb',
        version: -1,
        unsupported_families: [],
        categories: ['notification'],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'dnd_forwardslash',
        version: -1,
        unsupported_families: [],
        categories: ['notification'],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'dirty_lens',
        version: -1,
        unsupported_families: [],
        categories: ['image'],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'directions_train',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
        aliasOf: 'directions_railway',
    },
    {
        name: 'directions_ferry',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
        aliasOf: 'directions_boat',
    },
    {
        name: 'dinner_dining',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'device_thermostat',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'delivery_dining',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'dashboard_customize',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'dangerous',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'exposure_minus_2',
        version: -1,
        unsupported_families: [],
        categories: ['image'],
        tags: [],
        sizes_px: [],
        aliasOf: 'exposure_minus_2',
    },
    {
        name: 'exposure_minus_1',
        version: -1,
        unsupported_families: [],
        categories: ['image'],
        tags: [],
        sizes_px: [],
        aliasOf: 'exposure_minus_1',
    },
    {
        name: 'expand',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'enhance_photo_translate',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'electric_rickshaw',
        version: -1,
        unsupported_families: [],
        categories: ['maps'],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'edit_off',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'format_underline',
        version: -1,
        unsupported_families: [],
        categories: ['editor'],
        tags: [],
        sizes_px: [],
        aliasOf: 'format_underlined',
    },
    {
        name: 'format_color_text',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'format_color_fill',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'fit_screen',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'fire_hydrant',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'filter_list_alt',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'file_upload',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'file_present',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'file_download_done',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'file_download',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'festival',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'favorite_outline',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'face_retouching_natural',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    { name: 'grid_view', version: -1, unsupported_families: [], categories: [], tags: [], sizes_px: [] },
    {
        name: 'goat',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'home_filled',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'highlight_remove',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'headset_off',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'hdr_enhanced_select',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    { name: 'hardware', version: -1, unsupported_families: [], categories: [], tags: [], sizes_px: [] },
    {
        name: 'hail',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'ios_share',
        version: -1,
        unsupported_families: [],
        categories: ['social'],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'invert_colors_on',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'inventory',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'info_outline',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'imagesearch_roller',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'icecream',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'keyboard_control',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    { name: 'lunch_dining', version: -1, unsupported_families: [], categories: ['places'], tags: [], sizes_px: [] },
    {
        name: 'logout',
        version: -1,
        unsupported_families: [],
        categories: ['action'],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'lock_outline',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'lock_clock',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'location_pin',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'location_history',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'local_restaurant',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'local_print_shop',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'local_attraction',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'liquor',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'lightbulb_outline',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'lightbulb',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'label_outline',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'label_important_outline',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'my_library_music',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'my_library_books',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'my_library_add',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    { name: 'multitrack_audio', version: -1, unsupported_families: [], categories: [], tags: [], sizes_px: [] },
    {
        name: 'mp',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'motorcycle',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'motion_photos_off',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    { name: 'monitor', version: -1, unsupported_families: [], categories: [], tags: [], sizes_px: [] },
    {
        name: 'mode_edit',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'mic_external_on',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'mic_external_off',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'messenger_outline',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'messenger',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'mark_as_unread',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    { name: 'margin', version: -1, unsupported_families: [], categories: [], tags: [], sizes_px: [] },
    {
        name: 'now_widgets',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'now_wallpaper',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'notifications_on',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'no_meals_ouline',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'nightlight_round',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'nightlife',
        version: -1,
        unsupported_families: [],
        categories: ['places'],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'network_wifi',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'network_cell',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    { name: 'outgoing_mail', version: -1, unsupported_families: [], categories: [], tags: [], sizes_px: [] },
    {
        name: 'outbox',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'offline_share',
        version: -1,
        unsupported_families: [],
        categories: ['social'],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'play_disabled',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'play_circle_fill',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'pivot_table_chart',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'pie_chart_outlined',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'photo_camera_front',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'photo_camera_back',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'person_add_alt',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'perm_device_info',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'perm_contact_cal',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'park',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'panorama_wide_angle_select',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'panorama_vertical_select',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'panorama_photosphere_select',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'panorama_photosphere',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'panorama_horizontal_select',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'panorama_fisheye',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'padding',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'quick_contacts_mail',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'quick_contacts_dialer',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    { name: 'rtt', version: -1, unsupported_families: [], categories: [], tags: [], sizes_px: [] },
    {
        name: 'reset_tv',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'replay_circle_filled',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'repeat_one_on',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'repeat_on',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'remove_moderator',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'remove_done',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'recommend',
        version: -1,
        unsupported_families: [],
        categories: ['action'],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'ramen_dining',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'railway_alert',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'radio_button_on',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
        aliasOf: 'radio_button_checked',
    },
    {
        name: 'radio_button_off',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
        aliasOf: 'radio_button_checked',
    },
    {
        name: 'system_update_tv',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'switch_account',
        version: -1,
        unsupported_families: [],
        categories: ['action'],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'swipe',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'swap_vert_circle',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'stream',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'stacked_bar_chart',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'sim_card_alert',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'signal_wifi_0_bar',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'signal_cellular_0_bar',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    { name: 'shuffle_on', version: -1, unsupported_families: [], categories: [], tags: [], sizes_px: [] },
    {
        name: 'shield',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'settings_display',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'sentiment_neutral',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'send_to_mobile',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'send_and_archive',
        version: -1,
        unsupported_families: [],
        categories: ['action'],
        tags: [],
        sizes_px: [],
    },
    { name: 'segment', version: -1, unsupported_families: [], categories: [], tags: [], sizes_px: [] },
    {
        name: 'sd',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'screen_search_desktop',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'schedule_send',
        version: -1,
        unsupported_families: [],
        categories: ['action'],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'saved_search',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'trending_neutral',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'thumb_up_off_alt',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'thumb_down_off_alt',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'theater_comedy',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'taxi_alert',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    { name: 'takeout_dining', version: -1, unsupported_families: [], categories: [], tags: [], sizes_px: [] },
    {
        name: 'tag',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'upload_file',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'volunteer_activism',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'view_in_ar',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'view_comfortable',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'video_collection',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'workspaces_outline',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'workspaces_filled',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'wb_twighlight',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'wb_shade',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'waterfall_chart',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'wallet_travel',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    {
        name: 'wallet_membership',
        version: -1,
        unsupported_families: [],
        categories: [],
        tags: [],
        sizes_px: [],
    },
    { name: 'wallet_giftcard', version: -1, unsupported_families: [], categories: [], tags: [], sizes_px: [] },
];
